services:
    mongo:
        container_name: mongo
        restart: always
        image: mongo:4.2.8
        ports:
          - "27017:27017"
        volumes:
          - ./mongo/db:/data/db
          - ./mongo/configdb:/data/configdb
          - ./mongo/init:/docker-entrypoint-initdb.d
        environment:
          MONGO_INITDB_DATABASE: Sakepedia
          TZ: Asia/Tokyo
